project:
  type: website
  output-dir: docs

website:
  title: "Huda Sahaf"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - href: Cybersecurity Resume_HS.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

